import Verbose.Tactics.Notations
import Verbose.Portuguese.Assume
import Verbose.Portuguese.By
import Verbose.Portuguese.Calc
import Verbose.Portuguese.Claim
import Verbose.Portuguese.Fix
import Verbose.Portuguese.Lets
import Verbose.Portuguese.Sinces
import Verbose.Portuguese.We
import Verbose.Portuguese.Widget
import Verbose.Portuguese.Statements
